/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsString,
  MaxLength,
  IsOptional,
  IsBoolean,
  IsNumber,
  Min,
  Max,
  ValidateNested,
} from "class-validator";

import { ProductUpdateManyWithoutOrdersInput } from "./ProductUpdateManyWithoutOrdersInput";
import { Type } from "class-transformer";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { AmazonDatumrWhereUniqueInput } from "../../amazonDatumr/base/AmazonDatumrWhereUniqueInput";

@InputType()
class OrderUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  payment?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  paymentStatus?: boolean | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;

  @ApiProperty({
    required: false,
    type: () => ProductUpdateManyWithoutOrdersInput,
  })
  @ValidateNested()
  @Type(() => ProductUpdateManyWithoutOrdersInput)
  @IsOptional()
  @Field(() => ProductUpdateManyWithoutOrdersInput, {
    nullable: true,
  })
  products?: ProductUpdateManyWithoutOrdersInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  status?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => AmazonDatumrWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AmazonDatumrWhereUniqueInput)
  @IsOptional()
  @Field(() => AmazonDatumrWhereUniqueInput, {
    nullable: true,
  })
  user?: AmazonDatumrWhereUniqueInput | null;
}

export { OrderUpdateInput as OrderUpdateInput };
