/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AmazonDatumr } from "./AmazonDatumr";
import { AmazonDatumrCountArgs } from "./AmazonDatumrCountArgs";
import { AmazonDatumrFindManyArgs } from "./AmazonDatumrFindManyArgs";
import { AmazonDatumrFindUniqueArgs } from "./AmazonDatumrFindUniqueArgs";
import { CreateAmazonDatumrArgs } from "./CreateAmazonDatumrArgs";
import { UpdateAmazonDatumrArgs } from "./UpdateAmazonDatumrArgs";
import { DeleteAmazonDatumrArgs } from "./DeleteAmazonDatumrArgs";
import { OrderFindManyArgs } from "../../order/base/OrderFindManyArgs";
import { Order } from "../../order/base/Order";
import { Review } from "../../review/base/Review";
import { AmazonDatumrService } from "../amazonDatumr.service";
@graphql.Resolver(() => AmazonDatumr)
export class AmazonDatumrResolverBase {
  constructor(protected readonly service: AmazonDatumrService) {}

  async _amazonDatumrsMeta(
    @graphql.Args() args: AmazonDatumrCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AmazonDatumr])
  async amazonDatumrs(
    @graphql.Args() args: AmazonDatumrFindManyArgs
  ): Promise<AmazonDatumr[]> {
    return this.service.amazonDatumrs(args);
  }

  @graphql.Query(() => AmazonDatumr, { nullable: true })
  async amazonDatumr(
    @graphql.Args() args: AmazonDatumrFindUniqueArgs
  ): Promise<AmazonDatumr | null> {
    const result = await this.service.amazonDatumr(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AmazonDatumr)
  async createAmazonDatumr(
    @graphql.Args() args: CreateAmazonDatumrArgs
  ): Promise<AmazonDatumr> {
    return await this.service.createAmazonDatumr({
      ...args,
      data: {
        ...args.data,

        reviews: args.data.reviews
          ? {
              connect: args.data.reviews,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => AmazonDatumr)
  async updateAmazonDatumr(
    @graphql.Args() args: UpdateAmazonDatumrArgs
  ): Promise<AmazonDatumr | null> {
    try {
      return await this.service.updateAmazonDatumr({
        ...args,
        data: {
          ...args.data,

          reviews: args.data.reviews
            ? {
                connect: args.data.reviews,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => AmazonDatumr)
  async deleteAmazonDatumr(
    @graphql.Args() args: DeleteAmazonDatumrArgs
  ): Promise<AmazonDatumr | null> {
    try {
      return await this.service.deleteAmazonDatumr(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Order], { name: "orders" })
  async findOrders(
    @graphql.Parent() parent: AmazonDatumr,
    @graphql.Args() args: OrderFindManyArgs
  ): Promise<Order[]> {
    const results = await this.service.findOrders(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Review, {
    nullable: true,
    name: "reviews",
  })
  async getReviews(
    @graphql.Parent() parent: AmazonDatumr
  ): Promise<Review | null> {
    const result = await this.service.getReviews(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
