/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  AmazonDatumr as PrismaAmazonDatumr,
  Order as PrismaOrder,
  Review as PrismaReview,
} from "@prisma/client";

export class AmazonDatumrServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.AmazonDatumrCountArgs, "select">
  ): Promise<number> {
    return this.prisma.amazonDatumr.count(args);
  }

  async amazonDatumrs(
    args: Prisma.AmazonDatumrFindManyArgs
  ): Promise<PrismaAmazonDatumr[]> {
    return this.prisma.amazonDatumr.findMany(args);
  }
  async amazonDatumr(
    args: Prisma.AmazonDatumrFindUniqueArgs
  ): Promise<PrismaAmazonDatumr | null> {
    return this.prisma.amazonDatumr.findUnique(args);
  }
  async createAmazonDatumr(
    args: Prisma.AmazonDatumrCreateArgs
  ): Promise<PrismaAmazonDatumr> {
    return this.prisma.amazonDatumr.create(args);
  }
  async updateAmazonDatumr(
    args: Prisma.AmazonDatumrUpdateArgs
  ): Promise<PrismaAmazonDatumr> {
    return this.prisma.amazonDatumr.update(args);
  }
  async deleteAmazonDatumr(
    args: Prisma.AmazonDatumrDeleteArgs
  ): Promise<PrismaAmazonDatumr> {
    return this.prisma.amazonDatumr.delete(args);
  }

  async findOrders(
    parentId: string,
    args: Prisma.OrderFindManyArgs
  ): Promise<PrismaOrder[]> {
    return this.prisma.amazonDatumr
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .orders(args);
  }

  async getReviews(parentId: string): Promise<PrismaReview | null> {
    return this.prisma.amazonDatumr
      .findUnique({
        where: { id: parentId },
      })
      .reviews();
  }
}
