/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AmazonDatumrService } from "../amazonDatumr.service";
import { AmazonDatumrCreateInput } from "./AmazonDatumrCreateInput";
import { AmazonDatumr } from "./AmazonDatumr";
import { AmazonDatumrFindManyArgs } from "./AmazonDatumrFindManyArgs";
import { AmazonDatumrWhereUniqueInput } from "./AmazonDatumrWhereUniqueInput";
import { AmazonDatumrUpdateInput } from "./AmazonDatumrUpdateInput";
import { OrderFindManyArgs } from "../../order/base/OrderFindManyArgs";
import { Order } from "../../order/base/Order";
import { OrderWhereUniqueInput } from "../../order/base/OrderWhereUniqueInput";

export class AmazonDatumrControllerBase {
  constructor(protected readonly service: AmazonDatumrService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AmazonDatumr })
  async createAmazonDatumr(
    @common.Body() data: AmazonDatumrCreateInput
  ): Promise<AmazonDatumr> {
    return await this.service.createAmazonDatumr({
      data: {
        ...data,

        reviews: data.reviews
          ? {
              connect: data.reviews,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        isAdmin: true,

        reviews: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [AmazonDatumr] })
  @ApiNestedQuery(AmazonDatumrFindManyArgs)
  async amazonDatumrs(@common.Req() request: Request): Promise<AmazonDatumr[]> {
    const args = plainToClass(AmazonDatumrFindManyArgs, request.query);
    return this.service.amazonDatumrs({
      ...args,
      select: {
        createdAt: true,
        id: true,
        isAdmin: true,

        reviews: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AmazonDatumr })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async amazonDatumr(
    @common.Param() params: AmazonDatumrWhereUniqueInput
  ): Promise<AmazonDatumr | null> {
    const result = await this.service.amazonDatumr({
      where: params,
      select: {
        createdAt: true,
        id: true,
        isAdmin: true,

        reviews: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AmazonDatumr })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAmazonDatumr(
    @common.Param() params: AmazonDatumrWhereUniqueInput,
    @common.Body() data: AmazonDatumrUpdateInput
  ): Promise<AmazonDatumr | null> {
    try {
      return await this.service.updateAmazonDatumr({
        where: params,
        data: {
          ...data,

          reviews: data.reviews
            ? {
                connect: data.reviews,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          isAdmin: true,

          reviews: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AmazonDatumr })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAmazonDatumr(
    @common.Param() params: AmazonDatumrWhereUniqueInput
  ): Promise<AmazonDatumr | null> {
    try {
      return await this.service.deleteAmazonDatumr({
        where: params,
        select: {
          createdAt: true,
          id: true,
          isAdmin: true,

          reviews: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/orders")
  @ApiNestedQuery(OrderFindManyArgs)
  async findOrders(
    @common.Req() request: Request,
    @common.Param() params: AmazonDatumrWhereUniqueInput
  ): Promise<Order[]> {
    const query = plainToClass(OrderFindManyArgs, request.query);
    const results = await this.service.findOrders(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        payment: true,
        paymentStatus: true,
        price: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/orders")
  async connectOrders(
    @common.Param() params: AmazonDatumrWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        connect: body,
      },
    };
    await this.service.updateAmazonDatumr({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/orders")
  async updateOrders(
    @common.Param() params: AmazonDatumrWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        set: body,
      },
    };
    await this.service.updateAmazonDatumr({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/orders")
  async disconnectOrders(
    @common.Param() params: AmazonDatumrWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        disconnect: body,
      },
    };
    await this.service.updateAmazonDatumr({
      where: params,
      data,
      select: { id: true },
    });
  }
}
